#!/usr/bin/env python3
"""Import the FINAL Scenario-3 sample into the IndoHiTAB app after v9 migration.

This importer is designed for the five final CSVs generated by indohitab_hitab.ipynb:
  - tables_sample.csv
  - qa_sample.csv
  - batches.csv
  - pilot_tables.csv
  - pilot_qa.csv

Important properties:
- preserves users; it never deletes anything;
- validates table/QA/batch/pilot consistency before touching Supabase;
- reloads canonical HiTab rows directly from Hugging Face (kasnerz/hitab), so
  dataset_split is recovered correctly for export as train/test/dev JSONL;
- normalizes Hugging Face string/literal fields before comparing them with CSV,
  avoiding false mismatches caused by CSV/Pandas dtype conversion;
- keeps assignment empty after import; Admin assigns by batch/table in the app.

Dry run:
  python3 scripts/import_final_sample.py --sample-dir final_sample

Apply (after RESET_DATASET_KEEP_USERS.sql):
  export SUPABASE_URL='https://...supabase.co'
  export SUPABASE_SERVICE_ROLE_KEY='...'
  python3 scripts/import_final_sample.py --sample-dir final_sample --apply
"""
from __future__ import annotations

import argparse
import ast
import collections
import csv
import json
import os
import sys
import uuid
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

NAMESPACE = uuid.UUID("c9e4e1a7-27a7-4bac-a7a6-c7bc1289ca37")
SOURCE_ID = {"nsc": 1, "nsf": 2, "statcan": 3, "totto": 4}
QA_FIELDS = [
    "id", "table_id", "table_source", "sentence_id", "sub_sentence_id",
    "sub_sentence", "question", "answer", "aggregation", "linked_cells",
    "answer_formulas", "reference_cells_map",
]


def stable(kind: str, value: str) -> str:
    return str(uuid.uuid5(NAMESPACE, f"{kind}:{value}"))


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def parse_literal(value: Any) -> Any:
    if not isinstance(value, str):
        return value
    s = value.strip()
    if not s:
        return value
    for fn in (json.loads, ast.literal_eval):
        try:
            return fn(s)
        except Exception:
            pass
    return value


def boolish(value: Any) -> bool:
    return str(value).strip().lower() in {"1", "true", "t", "yes", "y"}


def normalize_hf_value(value: Any) -> Any:
    if hasattr(value, "tolist"):
        return value.tolist()
    if isinstance(value, dict):
        return {k: normalize_hf_value(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [normalize_hf_value(v) for v in value]
    return value


def load_hitab(dataset_name: str, revision: str | None):
    try:
        from datasets import load_dataset
    except ImportError as exc:
        raise SystemExit("Install dependency first: python3 -m pip install -U datasets") from exc

    ds = load_dataset(dataset_name, revision=revision)
    qa_by_id: dict[str, dict[str, Any]] = {}
    split_by_id: dict[str, str] = {}
    table_by_id: dict[str, dict[str, Any]] = {}

    for split, dataset in ds.items():
        for raw in dataset:
            row = {k: normalize_hf_value(v) for k, v in dict(raw).items()}
            qid = str(row["id"])
            tid = str(row["table_id"])
            if qid in qa_by_id:
                raise ValueError(f"Duplicate QA id in Hugging Face dataset: {qid}")

            content = parse_literal(row.get("table_content"))
            if not isinstance(content, dict):
                raise ValueError(f"Malformed table_content for table {tid}")

            prior = table_by_id.get(tid)
            if prior is not None and prior != content:
                raise ValueError(f"Inconsistent table_content in Hugging Face for table {tid}")
            table_by_id[tid] = content

            # Normalize the canonical Hugging Face QA into the SAME semantic
            # representation used for CSV validation. In kasnerz/hitab these
            # columns are stored as strings (including list/dict literals), while
            # pandas/CSV round-tripping may alter scalar dtypes.
            qa = {
                "id": qid,
                "table_id": tid,
                "table_source": str(row.get("table_source", "") or "").strip(),
                "sentence_id": "" if row.get("sentence_id") is None else str(row.get("sentence_id")),
                "sub_sentence_id": "" if row.get("sub_sentence_id") is None else str(row.get("sub_sentence_id")),
                "sub_sentence": "" if row.get("sub_sentence") is None else str(row.get("sub_sentence")),
                "question": "" if row.get("question") is None else str(row.get("question")),
                "answer": parse_literal(row.get("answer")),
                "aggregation": parse_literal(row.get("aggregation")),
                "linked_cells": parse_literal(row.get("linked_cells")),
                "answer_formulas": parse_literal(row.get("answer_formulas")),
                "reference_cells_map": parse_literal(row.get("reference_cells_map")),
            }
            qa_by_id[qid] = qa
            split_by_id[qid] = str(split)

    return table_by_id, qa_by_id, split_by_id


def normalize_csv_qa(row: dict[str, str]) -> dict[str, Any]:
    # Keep sentence_id/sub_sentence_id as strings because that is the canonical
    # schema in kasnerz/hitab. Do not coerce them to int.
    return {
        "id": str(row["id"]).strip(),
        "table_id": str(row["table_id"]).strip(),
        "table_source": str(row["table_source"]).strip(),
        "sentence_id": str(row.get("sentence_id", "") or "").strip(),
        "sub_sentence_id": str(row.get("sub_sentence_id", "") or "").strip(),
        "sub_sentence": str(row.get("sub_sentence", "") or ""),
        "question": str(row.get("question", "") or ""),
        "answer": parse_literal(row.get("answer", "")),
        "aggregation": parse_literal(row.get("aggregation", "")),
        "linked_cells": parse_literal(row.get("linked_cells", "")),
        "answer_formulas": parse_literal(row.get("answer_formulas", "")),
        "reference_cells_map": parse_literal(row.get("reference_cells_map", "")),
    }


def qa_diff(left: dict[str, Any], right: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Return field-level differences to make validation failures diagnosable."""
    diffs: dict[str, dict[str, Any]] = {}
    for key in QA_FIELDS:
        if left.get(key) != right.get(key):
            diffs[key] = {
                "csv": left.get(key),
                "canonical": right.get(key),
            }
    return diffs


def validate_and_build(sample_dir: Path, dataset_name: str, revision: str | None):
    tables_rows = read_csv(sample_dir / "tables_sample.csv")
    qa_rows = read_csv(sample_dir / "qa_sample.csv")
    batch_rows = read_csv(sample_dir / "batches.csv")
    pilot_table_rows = read_csv(sample_dir / "pilot_tables.csv")
    pilot_qa_rows = read_csv(sample_dir / "pilot_qa.csv")

    table_csv = {str(r["table_id"]): r for r in tables_rows}
    qa_csv = {str(r["id"]): r for r in qa_rows}
    batches = {str(r["table_id"]): r for r in batch_rows}
    pilot_tables = {str(r["table_id"]) for r in pilot_table_rows}
    pilot_qa = {str(r["id"]) for r in pilot_qa_rows}

    if len(table_csv) != len(tables_rows):
        raise ValueError("Duplicate table_id in tables_sample.csv")
    if len(qa_csv) != len(qa_rows):
        raise ValueError("Duplicate QA id in qa_sample.csv")
    if set(table_csv) != set(batches):
        raise ValueError("batches.csv must contain exactly the same table IDs as tables_sample.csv")
    if not pilot_tables <= set(table_csv):
        raise ValueError("pilot_tables.csv contains a table outside tables_sample.csv")
    if not pilot_qa <= set(qa_csv):
        raise ValueError("pilot_qa.csv contains a QA outside qa_sample.csv")

    q_by_table: dict[str, list[dict[str, str]]] = collections.defaultdict(list)
    for r in qa_rows:
        tid = str(r["table_id"])
        if tid not in table_csv:
            raise ValueError(f"QA {r['id']} points to unselected table {tid}")
        q_by_table[tid].append(r)

    missing_qa = sorted(set(table_csv) - set(q_by_table))
    if missing_qa:
        raise ValueError(f"Selected table(s) without QA: {missing_qa[:10]}")

    for tid, b in batches.items():
        if int(b["qa_count"]) != len(q_by_table[tid]):
            raise ValueError(f"qa_count mismatch for table {tid}")
        if boolish(b.get("is_pilot", "")) != (tid in pilot_tables):
            raise ValueError(f"Pilot flag mismatch for table {tid}")

    expected_pilot_qa = {
        str(r["id"])
        for tid in pilot_tables
        for r in q_by_table[tid]
    }
    if expected_pilot_qa != pilot_qa:
        raise ValueError("pilot_qa.csv must contain every QA from pilot tables and nothing else")

    hf_tables, hf_qa, hf_splits = load_hitab(dataset_name, revision)

    table_records = []
    cell_records = []
    qa_records = []

    for tid in sorted(table_csv):
        csv_row = table_csv[tid]
        source = str(csv_row["table_source"]).strip().lower()
        csv_content = parse_literal(csv_row["table_content"])
        if tid not in hf_tables:
            raise ValueError(f"Selected table missing from {dataset_name}: {tid}")
        canonical = hf_tables[tid]
        if csv_content != canonical:
            raise ValueError(f"tables_sample.csv differs from canonical HiTab table: {tid}")

        b = batches[tid]
        table_uuid = stable("table", tid)
        table_records.append({
            "id": table_uuid,
            "code": "HITAB:" + tid,
            "original_table_id": tid,
            "title_en": str(canonical["title"]),
            "original_table": canonical,
            "annotated_table": canonical,
            "validated_table": None,
            "annotate_flag": 1,
            "batch_no": int(b["batch"]),
            "is_pilot": boolish(b["is_pilot"]),
            "data_source_id": SOURCE_ID.get(source),
            "annotator_id": None,
            "validator_id": None,
            "assigned_to": None,
        })

        top = int(canonical.get("top_header_rows_num", 0) or 0)
        left = int(canonical.get("left_header_columns_num", 0) or 0)
        position = 0
        for rr, row in enumerate(canonical.get("texts", [])):
            for cc, value in enumerate(row):
                # Same translation workspace rule as the existing importer:
                # translate header/row-label cells, not numeric/body data cells.
                if (rr >= top and cc >= left) or value is None or not str(value).strip():
                    continue
                cell_records.append({
                    "id": stable("cell", f"{tid}:{rr}:{cc}"),
                    "table_id": table_uuid,
                    "row_index": rr,
                    "column_index": cc,
                    "position": position,
                    "kind": "header" if rr < top else "column",
                    "source_text": str(value),
                })
                position += 1

    pos_by_table = collections.defaultdict(int)
    for r in qa_rows:
        qid = str(r["id"])
        tid = str(r["table_id"])
        if qid not in hf_qa:
            raise ValueError(f"Selected QA missing from {dataset_name}: {qid}")

        csv_qa = normalize_csv_qa(r)
        canonical = hf_qa[qid]
        if str(canonical["table_id"]) != tid:
            raise ValueError(f"QA {qid} canonical parent mismatch")
        if csv_qa != canonical:
            diffs = qa_diff(csv_qa, canonical)
            preview = "; ".join(
                f"{field}: csv={values['csv']!r} canonical={values['canonical']!r}"
                for field, values in list(diffs.items())[:5]
            )
            raise ValueError(
                f"qa_sample.csv differs from canonical HiTab QA: {qid}. "
                f"Differing field(s): {preview}"
            )

        answer = canonical.get("answer")
        answer_en = ", ".join(str(v) for v in answer) if isinstance(answer, list) else str(answer)
        b = batches[tid]
        pos = pos_by_table[tid]
        pos_by_table[tid] += 1

        qa_records.append({
            "id": stable("qa", qid),
            "table_id": stable("table", tid),
            "original_question_id": qid,
            "position": pos,
            "question_en": str(canonical["question"]),
            "answer_en": answer_en,
            "original_qa": canonical,
            "annotated_qa": canonical,
            "validated_qa": None,
            "dataset_split": hf_splits[qid],
            "annotate_flag": 1,
            "batch_no": int(b["batch"]),
            "is_pilot": boolish(b["is_pilot"]),
            "data_source_id": SOURCE_ID.get(str(r["table_source"]).strip().lower()),
            "annotator_id": None,
            "validator_id": None,
        })

    return table_records, cell_records, qa_records


def chunks(records, size=50):
    for i in range(0, len(records), size):
        yield records[i:i + size]


def post_rows(url: str, key: str, table: str, records: list[dict[str, Any]]):
    endpoint = url.rstrip("/") + "/rest/v1/" + urllib.parse.quote(table)
    headers = {
        "apikey": key,
        "Content-Type": "application/json",
        "Prefer": "resolution=ignore-duplicates,return=minimal",
    }
    if not key.startswith("sb_secret_"):
        headers["Authorization"] = "Bearer " + key

    for i, batch in enumerate(chunks(records), 1):
        req = urllib.request.Request(
            endpoint,
            data=json.dumps(batch, ensure_ascii=False, allow_nan=False).encode(),
            headers=headers,
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=90) as resp:
                resp.read()
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(
                f"Import {table}, batch {i}, HTTP {exc.code}: {detail[:1200]}"
            ) from exc


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sample-dir", type=Path, required=True)
    parser.add_argument("--hitab-dataset", default="kasnerz/hitab")
    parser.add_argument("--hitab-revision", default=None)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    tables, cells, qa = validate_and_build(
        args.sample_dir,
        args.hitab_dataset,
        args.hitab_revision,
    )

    batch_tables = collections.Counter(r["batch_no"] for r in tables)
    batch_qa = collections.Counter(r["batch_no"] for r in qa)
    split_qa = collections.Counter(r["dataset_split"] for r in qa)
    source_tables = collections.Counter(r["data_source_id"] for r in tables)

    print(f"Validated FINAL sample: {len(tables)} tables / {len(qa)} QA / {len(cells)} translatable cells")
    print(f"Pilot: {sum(r['is_pilot'] for r in tables)} tables / {sum(r['is_pilot'] for r in qa)} QA")
    print("Batches:", ", ".join(
        f"B{b}={batch_tables[b]} tables/{batch_qa[b]} QA" for b in sorted(batch_tables)
    ))
    print("QA split:", dict(split_qa))
    print("Table datasource IDs:", dict(source_tables))

    if not args.apply:
        print("DRY RUN: database untouched.")
        return

    url = os.environ.get("SUPABASE_URL", "").strip()
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "").strip()
    if not url.startswith("https://") or not key:
        raise SystemExit("Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in this terminal.")

    for table_name, records in (
        ("tqa_tables", tables),
        ("table_cells", cells),
        ("qa_pairs", qa),
    ):
        print(f"Inserting {table_name}: {len(records)} rows")
        post_rows(url, key, table_name, records)

    print("Import finished. Assign users afterward from Penugasan by batch or individual table.")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, RuntimeError, SyntaxError) as exc:
        print("ERROR:", exc, file=sys.stderr)
        raise SystemExit(1)
