/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDasborRouteImport } from './routes/_authenticated/dasbor'
import { Route as AuthenticatedPenggunaRouteImport } from './routes/_authenticated/pengguna'
import { Route as AuthenticatedPemeriksaanIndexRouteImport } from './routes/_authenticated/pemeriksaan.index'
import { Route as AuthenticatedTerjemahanIndexRouteImport } from './routes/_authenticated/terjemahan.index'
import { Route as AuthenticatedTerjemahanTableIdRouteImport } from './routes/_authenticated/terjemahan.$tableId'
import { Route as AuthenticatedPemeriksaanJenisIdRouteImport } from './routes/_authenticated/pemeriksaan.$jenis.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDasborRoute = AuthenticatedDasborRouteImport.update({
  id: '/dasbor',
  path: '/dasbor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenggunaRoute = AuthenticatedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPemeriksaanIndexRoute =
  AuthenticatedPemeriksaanIndexRouteImport.update({
    id: '/pemeriksaan/',
    path: '/pemeriksaan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTerjemahanIndexRoute =
  AuthenticatedTerjemahanIndexRouteImport.update({
    id: '/terjemahan/',
    path: '/terjemahan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTerjemahanTableIdRoute =
  AuthenticatedTerjemahanTableIdRouteImport.update({
    id: '/terjemahan/$tableId',
    path: '/terjemahan/$tableId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPemeriksaanJenisIdRoute =
  AuthenticatedPemeriksaanJenisIdRouteImport.update({
    id: '/pemeriksaan/$jenis/$id',
    path: '/pemeriksaan/$jenis/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dasbor': typeof AuthenticatedDasborRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/terjemahan/$tableId': typeof AuthenticatedTerjemahanTableIdRoute
  '/pemeriksaan/': typeof AuthenticatedPemeriksaanIndexRoute
  '/terjemahan/': typeof AuthenticatedTerjemahanIndexRoute
  '/pemeriksaan/$jenis/$id': typeof AuthenticatedPemeriksaanJenisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dasbor': typeof AuthenticatedDasborRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/terjemahan/$tableId': typeof AuthenticatedTerjemahanTableIdRoute
  '/pemeriksaan': typeof AuthenticatedPemeriksaanIndexRoute
  '/terjemahan': typeof AuthenticatedTerjemahanIndexRoute
  '/pemeriksaan/$jenis/$id': typeof AuthenticatedPemeriksaanJenisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dasbor': typeof AuthenticatedDasborRoute
  '/_authenticated/pengguna': typeof AuthenticatedPenggunaRoute
  '/_authenticated/terjemahan/$tableId': typeof AuthenticatedTerjemahanTableIdRoute
  '/_authenticated/pemeriksaan/': typeof AuthenticatedPemeriksaanIndexRoute
  '/_authenticated/terjemahan/': typeof AuthenticatedTerjemahanIndexRoute
  '/_authenticated/pemeriksaan/$jenis/$id': typeof AuthenticatedPemeriksaanJenisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dasbor'
    | '/pengguna'
    | '/terjemahan/$tableId'
    | '/pemeriksaan/'
    | '/terjemahan/'
    | '/pemeriksaan/$jenis/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dasbor'
    | '/pengguna'
    | '/terjemahan/$tableId'
    | '/pemeriksaan'
    | '/terjemahan'
    | '/pemeriksaan/$jenis/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dasbor'
    | '/_authenticated/pengguna'
    | '/_authenticated/terjemahan/$tableId'
    | '/_authenticated/pemeriksaan/'
    | '/_authenticated/terjemahan/'
    | '/_authenticated/pemeriksaan/$jenis/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dasbor': {
      id: '/_authenticated/dasbor'
      path: '/dasbor'
      fullPath: '/dasbor'
      preLoaderRoute: typeof AuthenticatedDasborRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengguna': {
      id: '/_authenticated/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthenticatedPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pemeriksaan/': {
      id: '/_authenticated/pemeriksaan/'
      path: '/pemeriksaan'
      fullPath: '/pemeriksaan/'
      preLoaderRoute: typeof AuthenticatedPemeriksaanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terjemahan/': {
      id: '/_authenticated/terjemahan/'
      path: '/terjemahan'
      fullPath: '/terjemahan/'
      preLoaderRoute: typeof AuthenticatedTerjemahanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terjemahan/$tableId': {
      id: '/_authenticated/terjemahan/$tableId'
      path: '/terjemahan/$tableId'
      fullPath: '/terjemahan/$tableId'
      preLoaderRoute: typeof AuthenticatedTerjemahanTableIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pemeriksaan/$jenis/$id': {
      id: '/_authenticated/pemeriksaan/$jenis/$id'
      path: '/pemeriksaan/$jenis/$id'
      fullPath: '/pemeriksaan/$jenis/$id'
      preLoaderRoute: typeof AuthenticatedPemeriksaanJenisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDasborRoute: typeof AuthenticatedDasborRoute
  AuthenticatedPenggunaRoute: typeof AuthenticatedPenggunaRoute
  AuthenticatedTerjemahanTableIdRoute: typeof AuthenticatedTerjemahanTableIdRoute
  AuthenticatedPemeriksaanIndexRoute: typeof AuthenticatedPemeriksaanIndexRoute
  AuthenticatedTerjemahanIndexRoute: typeof AuthenticatedTerjemahanIndexRoute
  AuthenticatedPemeriksaanJenisIdRoute: typeof AuthenticatedPemeriksaanJenisIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDasborRoute: AuthenticatedDasborRoute,
  AuthenticatedPenggunaRoute: AuthenticatedPenggunaRoute,
  AuthenticatedTerjemahanTableIdRoute: AuthenticatedTerjemahanTableIdRoute,
  AuthenticatedPemeriksaanIndexRoute: AuthenticatedPemeriksaanIndexRoute,
  AuthenticatedTerjemahanIndexRoute: AuthenticatedTerjemahanIndexRoute,
  AuthenticatedPemeriksaanJenisIdRoute: AuthenticatedPemeriksaanJenisIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
